image: newsdev/go:1.3

services:
  - redis

env:
  - AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}}
  - AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}}

script:
  - make test
  - ./release.sh

notify:
  email:
    recipients:
      - eric.buth@nytimes.com
